version: '3.3'
services:
  site:
    image: quizbot
    environment:
      DEBUG: "true"
      USE_SOCKS5_PROXY: "true"
      SOCKS5_PROXY: "socks5h://138.68.75.100:8888"
      SOCKS5_PROXY_USER: "proxyuser"
      SOCKS5_PROXY_PASSWORD: "yyyxy7fg"
      USE_TELEGRAM_WEBHOOK: "false"
      TELEGRAM_TOKEN: "904055101:AAFnuJeIITnfegzGzxhrTad-Yd71cZpzNok"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    restart: always
    volumes:
      - "./data/bot_data:/usr/src/app/data"
    links:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb_data:/data/db"
